name: Package Testing

on:
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 UTC every day

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9, '3.10']
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Restore Ubuntu cache
        uses: actions/cache@v1
        if: matrix.operating-system == 'ubuntu-latest'
        with:
          path: ~/.cache/pip
          key: ${{ matrix.os }}-${{ matrix.python-version }}-${{ hashFiles('**/setup.py')}}
          restore-keys: ${{ matrix.os }}-${{ matrix.python-version }}-

      - name: Restore MacOS cache
        uses: actions/cache@v1
        if: matrix.operating-system == 'macos-latest'
        with:
          path: ~/Library/Caches/pip
          key: ${{ matrix.os }}-${{ matrix.python-version }}-${{ hashFiles('**/setup.py')}}
          restore-keys: ${{ matrix.os }}-${{ matrix.python-version }}-

      - name: Restore Windows cache
        uses: actions/cache@v1
        if: matrix.operating-system == 'windows-latest'
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ matrix.os }}-${{ matrix.python-version }}-${{ hashFiles('**/setup.py')}}
          restore-keys: ${{ matrix.os }}-${{ matrix.python-version }}-

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install PyTorch(1.10.2) and TorchVision(0.11.3) on Linux and Windows
        if: >
          matrix.operating-system == 'ubuntu-latest' ||
          matrix.operating-system == 'windows-latest'
        run: >
          pip install torch==1.10.2+cpu torchvision==0.11.3+cpu
          -f https://download.pytorch.org/whl/torch_stable.html

      - name: Install PyTorch(1.10.1) and TorchVision(0.11.2) on MacOS
        if: matrix.operating-system == 'macos-latest'
        run: pip install torch==1.10.1 torchvision==0.11.2

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install PyTorch(1.11.0) and TorchVision(0.12.0) on Linux and Windows
        if: >
          matrix.operating-system == 'ubuntu-latest' ||
          matrix.operating-system == 'windows-latest'
        run: >
          pip install torch==1.11.0+cpu torchvision==0.12.0+cpu
          -f https://download.pytorch.org/whl/torch_stable.html

      - name: Install pywhisper package from pypi
        run: >
          pip install .[dev]

      - name: Unittest
        run: |
          pytest tests